name: "GitHub Issue Labels"

on:
  issues:
    types: [labeled, unlabeled, reopened]

jobs:
  support:
    runs-on: ubuntu-latest
    steps:
      - name: Feature Request
        uses: dessant/support-requests@v2
        with:
          github-token: ${{ github.token }}
          support-label: "feature request"
          issue-comment: >
            Hi @{issue-author}! We use the issue tracker exclusively
            for bug reports and issues. However, this issue appears
            to be a feature request. Please use the [Discord](https://www.lunasea.app/discord)
            to request new features.
          close-issue: true
          lock-issue: true
          issue-lock-reason: "off-topic"

      - name: Support
        uses: dessant/support-requests@v2
        with:
          github-token: ${{ github.token }}
          support-label: "support"
          issue-comment: >
            Hi @{issue-author}! We use the issue tracker exclusively
            for bug reports and issues. However, this issue appears
            to be a support request. Please use the following channels:

            - [Discord](https://www.lunasea.app/discord)

            - [GitHub Discussions](https://github.com/JagandeepBrar/lunasea/discussions)

            - [Subreddit](https://www.lunasea.app/reddit)
          close-issue: true
          lock-issue: true
          issue-lock-reason: "off-topic"
